services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s